export const projects = [
  {
    id: 1,
    title: "AI-Powered School OS",
    category: "AI Development",
    categoryColor: "text-[#0057C8] dark:text-[#1A9FFF]",
    categoryBg: "bg-[#0057C8]/5 dark:bg-[#0057C8]/10",
    categoryBorder: "border-[#0057C8]/20 dark:border-[#0057C8]/20",
    gradient: "from-[#0057C8] via-[#1A9FFF] to-[#5CDD2B]",
    description:
      "Built India's first AI-driven school operating system — managing admissions, fees, attendance, and academic analytics for 500+ schools.",
    tags: ["Next.js", "TensorFlow", "PostgreSQL", "AWS"],
    stats: [
      { label: "Schools", value: "500+" },
      { label: "Students", value: "250K+" },
      { label: "Uptime", value: "99.9%" },
    ],
    featured: true,
    link: "https://www.learnxchain.com/",
  },
  {
    id: 2,
    title: "Teenz Skin",
    category: "E-Commerce",
    categoryColor: "text-[#FFC555] dark:text-[#FFC555]",
    categoryBg: "bg-[#FFC555]/5 dark:bg-[#FFC555]/10",
    categoryBorder: "border-[#FFC555]/20 dark:border-[#FFC555]/20",
    gradient: "from-[#FFC555] to-[#FF8C00]",
    description:
      "A skincare brand focused on safe and effective products for both children and adults. Emphasizes gentle formulations, skin health, and age-appropriate solutions.",
    tags: ["E-Commerce", "Skincare", "Health"],
    stats: [
      { label: "Customers", value: "10K+" },
      { label: "Products", value: "Safe" },
      { label: "Ages", value: "All" },
    ],
    featured: false,
    link: "https://www.teenzskin.com/",
  },
  {
    id: 3,
    title: "Anselmiller",
    category: "Corporate Web",
    categoryColor: "text-slate-600 dark:text-slate-400",
    categoryBg: "bg-slate-50 dark:bg-slate-500/10",
    categoryBorder: "border-slate-200/60 dark:border-slate-500/20",
    gradient: "from-slate-700 to-gray-900",
    description:
      "United States–based law firm delivering strategic legal solutions with a client-focused approach across various practice areas.",
    tags: ["Legal", "Corporate", "Services"],
    stats: [
      { label: "Clients", value: "10K+" },
      { label: "Base", value: "USA" },
      { label: "Quality", value: "Top tier" },
    ],
    featured: true,
    link: "https://www.anselmiller.com/",
  },
  {
    id: 4,
    title: "LXC Mobile App",
    category: "Mobile App",
    categoryColor: "text-[#0057C8] dark:text-[#1A9FFF]",
    categoryBg: "bg-[#0057C8]/5 dark:bg-[#0057C8]/10",
    categoryBorder: "border-[#0057C8]/20 dark:border-[#0057C8]/20",
    gradient: "from-[#0057C8] to-[#1A9FFF]",
    description:
      "The official LearnXChain mobile application providing seamless access to courses, student progress tracking, and community features on the go.",
    tags: ["React Native", "Node.js", "Firebase"],
    stats: [
      { label: "Downloads", value: "50K+" },
      { label: "Rating", value: "4.8★" },
      { label: "Active", value: "10K/mo" },
    ],
    featured: false,
    link: "https://play.google.com/store/apps/details?id=com.learnxchain.lxc&hl=en_IN",
  },
  {
    id: 5,
    title: "CineSync Booking",
    category: "Web Application",
    categoryColor: "text-[#1A9FFF] dark:text-[#1A9FFF]",
    categoryBg: "bg-[#1A9FFF]/5 dark:bg-[#1A9FFF]/10",
    categoryBorder: "border-[#1A9FFF]/20 dark:border-[#1A9FFF]/20",
    gradient: "from-[#1A9FFF] to-[#0057C8]",
    description:
      "A comprehensive platform for movie reviews and event bookings, featuring real-time seat selection, integrated ticketing, and community ratings.",
    tags: ["Next.js", "Stripe", "Prisma"],
    stats: [
      { label: "Bookings", value: "100K+" },
      { label: "Venues", value: "200+" },
      { label: "Reviews", value: "50K+" },
    ],
    featured: false,
    link: "",
  },
  {
    id: 6,
    title: "Singla Tour & Travels",
    category: "Travel & Tourism",
    categoryColor: "text-[#5CDD2B] dark:text-[#5CDD2B]",
    categoryBg: "bg-[#5CDD2B]/5 dark:bg-[#5CDD2B]/10",
    categoryBorder: "border-[#5CDD2B]/20 dark:border-[#5CDD2B]/20",
    gradient: "from-[#5CDD2B] to-[#4BBD22]",
    description:
      "Experience the breathtaking landscapes of Himachal Pradesh and explore the diverse cultural heritage of India with customized tour packages and taxi bookings.",
    tags: ["Travel", "Tourism", "Booking"],
    stats: [
      { label: "Packages", value: "50+" },
      { label: "Cabs", value: "Available" },
      { label: "Happy Clients", value: "10K+" },
    ],
    featured: false,
    link: "https://singlatourandtravels.com/",
  },
  {
    id: 7,
    title: "Abhay Raj & Sons International",
    category: "Sustainable Fashion & Global Export",
    categoryColor: "text-[#5CDD2B] dark:text-[#5CDD2B]",
    categoryBg: "bg-[#5CDD2B]/5 dark:bg-[#5CDD2B]/10",
    categoryBorder: "border-[#5CDD2B]/20 dark:border-[#5CDD2B]/20",
    gradient: "from-[#FFC555] via-[#5CDD2B] to-[#0057C8]",
    description:
      "A leader in circular fashion and premier global exporter of 100% cashmere, recycled textiles, and luxury garments, transforming waste into high-grade sustainable yarn.",
    tags: ["Sustainable", "Cashmere", "Global Export", "Circular Fashion"],
    stats: [
      { label: "Exporter", value: "#1 Cashmere" },
      { label: "Certification", value: "GRS Certified" },
      { label: "Mission", value: "Go Green" },
    ],
    featured: false,
    link: "https://abhayrajsons.com",
  },
];
