import { ActiveStatus, UserSex } from "@prisma/client";
import { z } from "zod";

// Full internal student registration schema (used by admin flows)
export const registerStudentSchema = z.object({
  email: z.string().email("Invalid email format"),
  phone: z.string().optional().or(z.literal("")),
  name: z.string().min(1, "Name is required"),
  userName: z.string().optional(), // Username will be generated by backend if not provided
  sex: z.nativeEnum(UserSex, { errorMap: () => ({ message: "Please select a gender" }) }),
  bloodType: z.string().min(1, "Blood type is required"),
  primaryContact: z.string().optional(),
  academicYear: z.string().min(1, "Academic year is required"),
  admissionNo: z.string().optional(),
  admissionDate: z.string().min(1, "Admission date is required"),
  rollNo: z.string().min(1, "Roll number is required"),
  status: z.nativeEnum(ActiveStatus, { errorMap: () => ({ message: "Invalid status" }) }).optional(),
  dateOfBirth: z.string().min(1, "Date of birth is required").refine((date) => {
    const dob = new Date(date);
    return dob < new Date();
  }, "Date of birth must be in the past"),
  Religion: z.string().min(1, "Religion is required"),
  category: z.string().optional(),
  caste: z.string().optional(),
  motherTongue: z.string().optional(),
  languagesKnown: z.string().optional(),

  fatherName: z.string().optional(),
  fatheremail: z.union([z.string().email("Invalid father's email format"), z.literal("")]).optional(),
  fatherPhone: z.string().optional(),
  fatherOccupation: z.string().optional(),

  motherName: z.string().optional(),
  motherOccupation: z.string().optional(),
  motherEmail: z.union([z.string().email("Invalid mother's email format"), z.literal("")]).optional(),
  motherPhone: z.string().optional(),

  guardianName: z.string().min(1, "Guardian name is required"),
  guardianRelation: z.string().min(1, "Guardian relation is required"),
  guardianEmail: z.string().email("Invalid guardian email format"),
  guardianPhone: z.string().optional().or(z.literal("")),
  guardianOccupation: z.string().optional(),
  guardianAddress: z.string().optional(),

  areSiblingStudying: z.string().optional(),
  siblingName: z.string().optional(),
  siblingClass: z.string().optional(),
  siblingRollNo: z.string().optional(),
  siblingAdmissionNo: z.string().optional(),

  currentAddress: z.string().min(1, "Current address is required"),
  permanentAddress: z.string().optional(),

  vehicleNumber: z.string().optional(),

  hostelName: z.string().optional(),
  roomNumber: z.string().optional(),

  medicalCondition: z.string().min(1, "Medical condition is required (enter 'None' if applicable)"),
  allergies: z.string().min(1, "Allergies information is required (enter 'None' if applicable)"),
  medicationName: z.string().optional(),

  schoolName: z.string().optional(),
  schoolId: z.string().cuid("Invalid school ID format"),
  classId: z.string().cuid("Invalid class ID format"),
  section: z.string().optional(),

  address: z.string().optional(),
  city: z.string().min(1, "City is required"),
  state: z.string().min(1, "State is required"),
  country: z.string().min(1, "Country is required"),
  pincode: z.string().min(1, "Pincode is required"),
  
  profilePicUrl: z.string().nullable().optional(), // Profile picture URL from uploaded file
  medicalCertificateUrl: z.string().optional(),
  transferCertificateUrl: z.string().optional(),
  className: z.string().optional(),
});

export const publicRegisterStudentSchema = z.object({
  email: z.string().email("Invalid email format"),
  phone: z.string().optional().or(z.literal("")),
  name: z.string().min(1, "Name is required"),
  sex: z.nativeEnum(UserSex, { errorMap: () => ({ message: "Please select a gender" }) }),
  bloodType: z.string().min(1, "Blood type is required"),
  academicYear: z.string().min(1, "Academic year is required"),
  dateOfBirth: z.string().min(1, "Date of birth is required").refine((date) => {
    const dob = new Date(date);
    return dob < new Date();
  }, "Date of birth must be in the past"),

  fatherName: z.string().optional(),
  fatherPhone: z.string().optional(),
  motherName: z.string().optional(),
  motherPhone: z.string().optional(),

  guardianName: z.string().min(1, "Guardian name is required"),
  guardianEmail: z.string().email("Invalid guardian email format"),
  guardianPhone: z.string().optional().or(z.literal("")),
  guardianRelation: z.string().min(1, "Guardian relation is required"),

  currentAddress: z.string().min(1, "Current address is required"),
  city: z.string().min(1, "City is required"),
  state: z.string().min(1, "State is required"),
  country: z.string().min(1, "Country is required"),
  pincode: z.string().min(1, "Pincode is required"),

  medicalCondition: z.string().min(1, "Medical condition is required (enter 'None' if applicable)"),
  allergies: z.string().min(1, "Allergies information is required (enter 'None' if applicable)"),

  schoolId: z.string().cuid("Invalid school ID format"),
  classId: z.string().cuid("Invalid class ID format"),
  section: z.string().optional(),
  className: z.string().optional(),
});


export const updateStudentSchema = registerStudentSchema.partial();
export const bulkStudentUploadSchema = z.array(registerStudentSchema);
