'use client';

import { motion } from 'motion/react';
import Link from 'next/link';
import { LandingNav } from '@/components/landing/LandingNav';
import { LandingFooter } from '@/components/landing/LandingFooter';
import { FileText, Users, Ban, AlertTriangle, Scale, RefreshCw } from 'lucide-react';

const sections = [
  {
    icon: <Users className="w-5 h-5" />,
    title: '1. Acceptance of Terms',
    content: [
      {
        subtitle: 'Agreement',
        text: 'By accessing or using RIT AI (available at ritai.learnxchain.in and related mobile applications), you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you must not use our platform.',
      },
      {
        subtitle: 'Eligibility',
        text: 'You must be at least 10 years old to use RIT AI. Users under 18 must have parental or guardian consent. By using the platform, you represent that you meet these eligibility requirements.',
      },
      {
        subtitle: 'Account Registration',
        text: 'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Notify us immediately at hello@learnxchain.in if you suspect unauthorised access.',
      },
    ],
  },
  {
    icon: <FileText className="w-5 h-5" />,
    title: '2. Use of the Platform',
    content: [
      {
        subtitle: 'Permitted Use',
        text: 'RIT AI is provided for personal, non-commercial educational use. You may access content, complete quizzes, interact with AI tutors, and use tools within the limits of your subscription plan.',
      },
      {
        subtitle: 'Prohibited Activities',
        text: 'You must not: attempt to reverse-engineer or scrape the platform; share account credentials; upload harmful, illegal, or offensive content; misuse the AI systems; circumvent access controls or subscription paywalls; or use the platform for commercial tutoring without a written agreement.',
      },
      {
        subtitle: 'AI-Generated Content',
        text: 'Content generated by our AI tools (doubt resolutions, summaries, career advice) is for educational guidance only and does not constitute professional advice. Always verify critical information with qualified educators.',
      },
    ],
  },
  {
    icon: <Scale className="w-5 h-5" />,
    title: '3. Intellectual Property',
    content: [
      {
        subtitle: 'Our Content',
        text: 'All content on RIT AI — including text, graphics, videos, AI models, course material, and software — is the intellectual property of LearnXChain Technologies Pvt. Ltd. or its licensors and is protected by Indian and international copyright laws.',
      },
      {
        subtitle: 'Limited License',
        text: 'We grant you a limited, non-exclusive, non-transferable, revocable licence to access and use the platform for personal educational purposes. This licence does not include the right to reproduce, distribute, or create derivative works from our content.',
      },
      {
        subtitle: 'User Content',
        text: 'By submitting notes, answers, or feedback on the platform, you grant LearnXChain a non-exclusive, royalty-free licence to use, store, and analyse that content to improve our services.',
      },
    ],
  },
  {
    icon: <Ban className="w-5 h-5" />,
    title: '4. Subscriptions & Payments',
    content: [
      {
        subtitle: 'Subscription Plans',
        text: 'RIT AI offers Free, Ignite (₹99/mo), Zenith Pro (₹199/mo), and Zenith Elite (₹299/mo) plans. Features and quotas vary by plan as described on our Pricing page. Prices are in Indian Rupees (INR) and inclusive of applicable taxes.',
      },
      {
        subtitle: 'Billing',
        text: 'Subscription fees are billed in advance on a monthly or annual basis. Payments are processed securely through Razorpay. By subscribing, you authorise us to charge your chosen payment method on a recurring basis.',
      },
      {
        subtitle: 'Price Changes',
        text: 'We reserve the right to modify subscription prices with 30 days\' advance notice. Continued use after the effective date constitutes acceptance of the new pricing.',
      },
    ],
  },
  {
    icon: <AlertTriangle className="w-5 h-5" />,
    title: '5. Disclaimers & Limitation of Liability',
    content: [
      {
        subtitle: 'No Warranty',
        text: 'RIT AI is provided "as is" and "as available" without any warranties of any kind, express or implied, including but not limited to fitness for a particular purpose, accuracy of AI-generated content, or uninterrupted availability.',
      },
      {
        subtitle: 'Limitation of Liability',
        text: 'To the maximum extent permitted by applicable law, LearnXChain\'s total liability for any claims arising from your use of the platform shall not exceed the amount paid by you in the 3 months immediately preceding the claim.',
      },
      {
        subtitle: 'Third-Party Links',
        text: 'RIT AI may contain links to third-party websites. We are not responsible for the content, privacy practices, or accuracy of any third-party sites.',
      },
    ],
  },
  {
    icon: <RefreshCw className="w-5 h-5" />,
    title: '6. Termination',
    content: [
      {
        subtitle: 'By Us',
        text: 'We reserve the right to suspend or terminate your account, without prior notice, if you violate these Terms and Conditions, engage in fraudulent activity, or use the platform in a manner harmful to others.',
      },
      {
        subtitle: 'By You',
        text: 'You may terminate your account at any time by visiting account settings or emailing hello@learnxchain.in. Termination does not entitle you to a refund of any prepaid subscription fees (see our Refund Policy).',
      },
    ],
  },
  {
    icon: <Scale className="w-5 h-5" />,
    title: '7. Governing Law & Dispute Resolution',
    content: [
      {
        subtitle: 'Governing Law',
        text: 'These Terms are governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in Rohtak, Haryana.',
      },
      {
        subtitle: 'Dispute Resolution',
        text: 'Before initiating legal proceedings, we encourage you to contact us at hello@learnxchain.in to resolve disputes amicably. We are committed to fair and prompt resolution of any concerns.',
      },
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#050d17] text-slate-900 dark:text-white font-sans">

      <div className="fixed inset-0 z-0 pointer-events-none overflow-hidden">
        <div
          className="absolute top-[-10%] right-[-5%] w-[40%] h-[40%] rounded-full blur-[140px] opacity-10"
          style={{ background: 'radial-gradient(circle, #5CDD2B 0%, transparent 70%)' }}
        />
      </div>

      <LandingNav />

      <div className="relative z-10 pt-16">
        {/* Hero */}
        <section className="max-w-4xl mx-auto px-6 sm:px-10 pt-16 pb-10 text-center">
          <motion.div initial={{ opacity: 0, scale: 0.85 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.4 }}
            className="w-16 h-16 rounded-2xl bg-linear-to-br from-[#5CDD2B] to-[#0057C8] flex items-center justify-center mx-auto mb-5 shadow-[0_12px_32px_rgba(92,221,43,0.25)]">
            <FileText className="w-8 h-8 text-white" />
          </motion.div>
          <motion.h1 initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.08 }}
            className="text-4xl sm:text-5xl font-black tracking-tight mb-3">
            Terms &amp;{' '}
            <span className="bg-linear-to-r from-[#5CDD2B] to-[#0057C8] bg-clip-text text-transparent">Conditions</span>
          </motion.h1>
          <motion.p initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.14 }}
            className="text-slate-500 dark:text-white/50 font-medium text-sm">
            Last updated: 29 May 2026 &nbsp;·&nbsp; Effective: 29 May 2026
          </motion.p>
          <motion.p initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.18 }}
            className="text-slate-500 dark:text-white/55 font-semibold max-w-2xl mx-auto mt-3">
            Please read these Terms and Conditions carefully before using the RIT AI platform operated by LearnXChain Technologies Pvt. Ltd.
          </motion.p>
        </section>

        {/* Content */}
        <section className="max-w-4xl mx-auto px-6 sm:px-10 pb-24 flex flex-col gap-5">
          {sections.map((section, i) => (
            <motion.div key={section.title}
              initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.04 }}
              className="rounded-2xl border border-slate-200 dark:border-white/10 bg-white dark:bg-[#0c1824] p-6 sm:p-8">
              <div className="flex items-center gap-3 mb-5">
                <div className="w-9 h-9 rounded-xl bg-[#5CDD2B]/10 flex items-center justify-center text-[#5CDD2B] shrink-0">
                  {section.icon}
                </div>
                <h2 className="text-base font-black text-slate-800 dark:text-white">{section.title}</h2>
              </div>
              <div className="flex flex-col gap-4">
                {section.content.map((item) => (
                  <div key={item.subtitle}>
                    <h3 className="text-sm font-bold text-slate-700 dark:text-white/80 mb-1">{item.subtitle}</h3>
                    <p className="text-sm text-slate-500 dark:text-white/50 leading-relaxed font-medium">{item.text}</p>
                  </div>
                ))}
              </div>
            </motion.div>
          ))}

          {/* Contact */}
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
            transition={{ duration: 0.4 }}
            className="rounded-2xl border border-[#5CDD2B]/20 bg-[#5CDD2B]/5 p-6 sm:p-8">
            <h2 className="text-base font-black text-slate-800 dark:text-white mb-2">8. Contact</h2>
            <p className="text-sm text-slate-500 dark:text-white/55 font-medium leading-relaxed">
              If you have questions about these Terms, contact us at{' '}
              <a href="mailto:hello@learnxchain.in" className="text-[#0057C8] dark:text-[#1A9FFF] font-bold hover:underline">hello@learnxchain.in</a>
              {' '}or write to: LearnXChain Technologies Pvt. Ltd., Rohtak, Haryana — 124001, India.
            </p>
          </motion.div>
        </section>

        <LandingFooter />
      </div>
    </div>
  );
}
